<html>
  <head>
    <title>Cloud Game Report</title>
    <link href="res/css/bootstrap.css" rel="stylesheet">
    <link href="res/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="res/css/intro.css" rel="stylesheet">
  </head>

  <body>
    <div class="container-narrow">

      <div class="masthead">
          <ul class="nav nav-pills pull-right">

          <li><a href="index.jsp">Home</a></li>
          <li ><a href="./signup">Sign up</a></li>
          <li class="active"><a href="about.jsp">About</a></li>
        </ul>
        <h2 >Cloud Game Report</h2>
      </div>

        <br><br>
      <div class="form-signin" style="max-width:400">
          <h2  align="Center" class="form-signin-heading">cloudgamereport | about</h2>
        <center>developed with love 
        <br><br>
        
        for more informations mail me at:<br><br>
        pedroorez (at) poli (dot) ufrj (dot) br</center>
      </div>
        <br><br>
        <div class="form-signin" style="max-width:800">
          <h2  align="Center" class="form-signin-heading">API | Manual</h2>
               
        <h4>First make the login with:</h4>
        http://cloudgamereport.herokuapp.com<b>/services/login/{GameID}/{UserName}/{CriptedPassword}</b><br>
        <ul>
        <li>{GameID} - Identificator of your Game<br>
        <li>{UserName} - User's Username<br>
        <li>{CriptedPassword} - User's Password<br></li>
        </ul>
        The service will return the session hashkey that you should save to use on the following services<br>
        
        <hr>
        
        <h4>List the Classes availables</h4>
        http://cloudgamereport.herokuapp.com<b>/services/ListOfAvailableClasses/{sessionhash}</b><br>
        <ul>
        <li>{sessionhash} - the session hashkey generated by the login service<br>
        </ul>
        This service will provide all the classes availables from the CloudGameReport<br>
        
        <hr>
        
        <h4>Request Subscription for a Class</h4>
        http://cloudgamereport.herokuapp.com<b>/services/SubscribeToClass/{sessionhash}/{ClassID}</b><br>
        <ul>
        <li>{ClassID} - Class identificator<br>
        <li>{sessionhash} - the session hashkey generated by the login service<br>
        </ul>
        Return true if the subscription is OKAY <br>
       
        <hr>
        
        <h4>List all classes that the user is subscribed</h4>
        http://cloudgamereport.herokuapp.com<b>/services/ListOfSubscribedGameEntries/{sessionhash}</b><br>
        <ul>
        <li>{sessionhash} - the session hashkey generated by the login service<br>
        </ul>
        The service will provide a list of all games from all the classes with your GameTypeID<br>
                
        <hr>
        
        <h4>Save a DataSet</h4>
        http://cloudgamereport.herokuapp.com<b>/services/Save/{sessionhash}/{GameEntry}/{data}</b><br>
        <ul>
        <li>{GameEntry} - The GameEntry ID (provided by "ListOfSubscribedGameEntries" service)<br>
        <li>{sessionhash} - the session hashkey generated by the login service<br>
        <li>{data} - The data that will be saved<br></li>
        </ul>
        The data must be in JSON format:<br>
        Example: {"pontuation_field" : "10", "SomeData" : "String"}
        
        <br><br>
        Will return true if everthing is fine <br>
        
        </div>
   

     <br><br>

      <div align="center" class="footer">
        <p>&copy; Pedro Correa - DEL - UFRJ 2014</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="res/js/jquery.js"></script>
    <script src="res/js/bootstrap-transition.js"></script>
    <script src="res/js/bootstrap-alert.js"></script>
    <script src="res/js/bootstrap-modal.js"></script>
    <script src="res/js/bootstrap-dropdown.js"></script>
    <script src="res/js/bootstrap-scrollspy.js"></script>
    <script src="res/js/bootstrap-tab.js"></script>
    <script src="res/js/bootstrap-tooltip.js"></script>
    <script src="res/js/bootstrap-popover.js"></script>
    <script src="res/js/bootstrap-button.js"></script>
    <script src="res/js/bootstrap-collapse.js"></script>
    <script src="res/js/bootstrap-carousel.js"></script>
    <script src="res/js/bootstrap-typeahead.js"></script>

  </body>
</html>
